services:
  wordpress:
    image: wordpress:6.4.1-php8.2-apache
    container_name: movie_wordpress
    restart: always
    environment:
      WORDPRESS_DB_USER: "movie_user"
      WORDPRESS_DB_PASSWORD: "movie_password"
      WORDPRESS_DB_NAME: "movie"
      LETSENCRYPT_HOST: localhost
      VIRTUAL_HOST: localhost
    depends_on:
      - mysql
    ports:
      - 127.0.0.1:9000:80
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - nginx-proxy

  mysql:
    image: mysql:8.2.0
    container_name: movie_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "movie"
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "movie_user"
      MYSQL_PASSWORD: "movie_password"
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true

